source 'https://rubygems.org'
gem 'pry'
gem 'pry-byebug'
gem 'restforce'
gem 'ruby-growl'
gem 'nokogiri'
gem 'omniauth-salesforce'
gem 'rubyzoho', git: "https://github.com/reedhein/rubyzoho.git"
gem 'sinatra'
gem 'haml'
gem 'data_mapper'
gem 'dm-sqlite-adapter'
gem 'activesupport'
gem 'gmail'
gem 'deepstruct'
gem 'watir'
gem 'selenium-webdriver'
gem 'databasedotcom'
gem 'mechanize'
gem 'boxr'


gem 'thin'
