ENV['CFLAGS'] = '-I/usr/local/Cellar/tesseract/3.04.01_2/include -I/usr/local/Cellar/leptonica/1.73/include'
ENV['LDFLAGS'] = '-L/usr/local/Cellar/tesseract/3.04.01_2/lib -L/usr/local/Cellar/leptonica/1.73/lib'
source 'https://rubygems.org'
gem 'pry'
gem 'pry-byebug'
gem 'restforce'
gem 'ruby-growl'
gem 'nokogiri'
gem 'omniauth-salesforce'
gem 'rubyzoho', git: "https://github.com/reedhein/rubyzoho.git"
gem 'sinatra'
gem 'haml'
gem 'data_mapper'
gem 'dm-sqlite-adapter'
gem 'activesupport'
gem 'gmail'
gem 'deepstruct'
gem 'watir'
gem 'watir-scroll'
gem 'selenium-webdriver'
gem 'databasedotcom'
gem 'mechanize'
gem 'boxr'
gem 'awesome_print'
gem 'pdf-reader'
gem 'tesseract-ocr'
gem 'thin'
gem 'rmagick'
gem 'grim'
gem 'classifier-reborn'
gem 'dhash'
gem 'faye'
